server:
  port: 8080

spring:
  application:
    name: AppUser
  datasource:
    username: 'new-social-user'
    url: jdbc:postgresql://localhost:5432/appuser
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'